### ISSUE TITLE
Interpreter is two times slower when targetting x86_64.

### ISSUE THREAD

**Issue by R030t1** [nielsAD/lape#105]
I will edit this post with compilation and execution times when I get the chance but the difference is on the scale of 1s for an empty script vs. 1ms for an empty script. I have had very basic scripts take around 10s to compile and execute (if I'm remembering properly).

**Comment by WarPie** [comment]
your timings are without doubt way off. Even an empty script wont use 1ms. Take running a script in simba for instance, you'd be imprting a buckload of functions, and then for every function and every variable lape will call ExposeGlobals, which builds a way for you to access vars and functions as as strings.. in all the base compilation time in compiling a script in simba is around 500ms depending on your CPU.

If you test in the lape editor which imports way less functions you'd still be looking at roughly 100ms to compile a blank script.

**Comment by R030t1** [comment]
I was using the head version of Simba and presumably the head version of Lape on Linux where PascalScript isn't even selectable. I might have been embellishing slightly and compile time might be closer to 10ms or 100ms. The same blank script would take 1-1.5s to compile on x86_64.

The reason I bothered to report this is because someone (maybe @nielsAD) mentioned offhandedly that this was an issue. It may have already been traced to an issue in FPC but that doesn't mean there are not issues using the software this tracker is attached to.

**Comment by nielsAD** [comment]
What compiler are you using? I am aware that x64 with FPC has been quite a lot slower compared to Delphi x64 and FPC x86, but with FPC 3 that has improved quite a lot. In the `lazarus-1.6` branch we are working on migrating towards FPC 3.

**Comment by WarPie** [comment]
I can not reproduce this on Windows. Runtime on x86-64 with < FPC3 is known to be slower, quite a lot slower. But I have never had compilation slowing down notably.
This issue seems specific to Linux, maybe even down to the FPC package used.

**Comment by 3FLLC** [comment]
FYI...Since I have products across the board, I can share:

Empty Source, Linux 64bit (1U Rack Server, Identical to 32bit Machine):
# time mp2 bench3
bench3 not found.

real	0m0.142s
user	0m0.046s
sys	0m0.005s

Empty Source, Linux 32bit:
# time mp2 bench3
bench3 not found.

real	0m0.041s
user	0m0.004s
sys	0m0.017s

* Both compiled with 3.0.2 FPC

Execution time, 64bit - 10 million calls to a function in the same script source:
# time mp2 bench2.p
HINT: Variable "Loop" not used at line 22, column 20 in file "bench2.p"

real	0m0.899s
user	0m0.776s
sys	0m0.008s

32bit Rack Server:
# time mp2 bench2
HINT: Variable "Loop" not used at line 21, column 20 in file "bench2.p"

real	0m0.588s
user	0m0.575s
sys	0m0.006s

* Obviously, 64bit is still slower - but, 300ms is nothing panic about - it is much closer than 2.6.4 was!

BENCH 2 SOURCE:
FUNCTION MKString(HowLong:Integer;OfWhat:Char):String;
Var
  Temp : String;
  T    : Integer;
Begin
  Temp := '';
  For T := 1 to HowLong do Temp := Temp + OfWhat;
  Result := Temp;
End;

Function MakeString(Howlong:Integer;OfWhat:Char):String;
Begin
   SetLength(Result,HowLong);
   FillChar(Result[1],HowLong,OfWhat);
End;

Begin
//   Writeln(MKString(60,'A'));
//   Writeln(MakeString(60,'A'));
//   For Var Loop:=1 to 1000000 do MkString(60,'A');
   For Var Loop:=1 to 1000000 do MakeString(60,'A');
End.

- If you would like, I can run the same build on Mac or Windows. My LA-PE sync is from  Aug 12, 2016. And I try to keep my LA-PE code as close to the original as possible, just a few compile defs and syntax extensions, oh, I also got rid of generics in the code (did speed it up a little bit).
