### ISSUE TITLE
Forwarding of type method

### ISSUE THREAD

**Issue by Olly-** [nielsAD/lape#43]
Type methods don't seem to automatically forward if needed, executing this code should explain all.

```
var CallMe: procedure of object;
type TFoo = type Pointer;
var Foo: TFoo;

procedure TFoo.Free; forward; //comment me to break shit.

procedure TFoo.Init;
begin
  CallMe := @Self.Free;
end;

procedure TFoo.Free;
begin
  Writeln('Free');
end;

begin
  Foo.Init;
  WriteLn(@CallMe);
  WriteLn(@Foo.Free);

  CallMe(); // Error: Access violation at line 22
end;       
```

**Comment by WarPie** [comment]
Actually there are two bugs here - testing with the bugfixes branch:
``` 
Compilation error: "Operator "Index" not compatible with types "Pointer" and "Int32" at line 214, column 26 in file "!addDelayedExpose""
```
This is caused by the forward declaration.

----
This would show the original error:
```pascal
var CallMe: procedure of object;
type TFoo = type Pointer;
var Foo: TFoo;

procedure TFoo.Free_Over;
begin Writeln('Free_Over');  end;

procedure TFoo.Init;
begin
  CallMe := @Self.Free_Under; //replace me with free_over to fix error
end;

procedure TFoo.Free_Under;
begin Writeln('Free_Under'); end;

begin
  Foo.Init;
  WriteLn(@CallMe);
  WriteLn(@Foo.Free_over);
  WriteLn(@Foo.Free_under);

  CallMe(); // Error: Access violation at line 22
end;
```

**Comment by nielsAD** [comment]
I fixed the bug when the method was forwarded ("index not compatible"). The second bug is actually undefined behaviour and is related to `AutoInvoke`. When the invoker tries to rewrite `Free_Under`, it skips the expression because it does not know it is actually a function. `CallMe := Self.Free_Under;` will work, but this is undefined behaviour and may break in future versions. For now, I have added some stricter type checks for methods and pointers to make sure the script above does not compile. Methods can only be assigned void pointers from now on.
